### ISSUE TITLE
Move non-shared modules out of the global dir

### ISSUE THREAD

**Issue by ltratt** [softdevteam/lua_benchmarking#24]
At the moment anything which a Lua benchmark wants to import ends up in `lualibs`. For modules which are shared between benchmarks, this is fine, but it's going to get very messy very quickly for anything which isn't shared. Let's move non-shared modules into the benchmark directories that use them, and have the benchmark update its global search path appropriately.

**Comment by fsfod** [comment]
Checking through all the modules it looks like its only luafun that isn't used by at least 2 benchmarks and our own jitstats module

**Comment by ltratt** [comment]
OK, let's move that one module out -- looks like a smaller job than we expected!
