### ISSUE TITLE
Add a mechanism for benchmarks to do any extra building necessary

### ISSUE THREAD

**Issue by ltratt** [softdevteam/lua_benchmarking#25]
Some benchmarks might need to build external libraries or do other work in order to run. We should allow benchmarks to have a `build.sh` script in their directory which is automatically run (the first time the benchmark is run? or when the top-level build is invoked?) to set things up. We may want to pass a specific `work` dir to this script so that benchmarks can avoid polluting global directories?

**Comment by ltratt** [comment]
Agreed. I think what I'd like to get to is that someone just types `build.sh` at the top-level and everything gets build for them.

**Comment by ltratt** [comment]
OK, so after discussing this, our consensus is that `simplerunner.lua` will, before running a benchmark `B`, see if a file `B/build.sh` exists. If it does, it will run that. It's then up to the `build.sh` script whether it checks to see if things are already built or not. If `build.sh` returns non-zero, `simplerunner.lua` will abort. Sound like a plan?

**Comment by fsfod** [comment]
fixed by #37
