### ISSUE TITLE
The number of benchmarks run should be a command line option

### ISSUE THREAD

**Issue by ltratt** [softdevteam/lua_benchmarking#30]
`simplerunner.lua` currently accepts a number as a final argument. This is ambiguous: we can't, for example, have a benchmark called "30". This argument should be moved to a command-line switch `-n`. This will also make it easier to allow multiple benchmarks to be specified on the command line.

**Comment by fsfod** [comment]
It does have a command line switch -c. It just seems silly to me ever name a benchmark a pure number

**Comment by ltratt** [comment]
You're right, so we don't need `-n`. We just need to remove the bit that interprets the last number as a count. You might think it's silly, but it's not so silly that someone won't do it. There's no need for us to give people a way of shooting themselves in the foot when they can use `-c` and guarantee to keep their foot out of danger.

**Comment by fsfod** [comment]
It was just a nice shortcut and i was making lots use it when testing stuff

**Comment by ltratt** [comment]
Fair enough. I think it needs to go though -- it's just an injury waiting to happen.

**Comment by ltratt** [comment]
This was fixed in #31.
